### PR TITLE
C [#COR-853] Add `shore/bootstrap` module in package.json

### PR DESCRIPTION
**Pull request by marufsiddiqui**
http://shore.myjetbrains.com/youtrack/issue/COR-853

@BenBach yet another one

### CODE REVIEW

**Comment by layflags** [comment]
Do we also have a ticket for integration the theme on the test page?

**Comment by marufsiddiqui** [comment]
@layflags should I do this as a part of this ticket or a new one?

**Comment by layflags** [comment]
@marufsiddiqui  we should add a new ticket for this!

**Comment by marufsiddiqui** [comment]
@layflags I've created the ticket for this http://shore.myjetbrains.com/youtrack/issue/COR-860

**Comment by eimfach** [comment]
Remember that you can easily integrate the theme by @import ''~@shore/bootstrap/...' in the main less file of the widget

**Comment by layflags** [comment]
:+1:

**Pull request merged**
